In [1]:
import numpy as np

## Basic Array creation

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
list = [1,2,3,4]
list

[1, 2, 3, 4]

In [5]:
np.array(list)

array([1, 2, 3, 4])

In [6]:
list = [[1,2,3],[4,5,6],[7,8,9]]
list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array generation function

In [9]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [10]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

## Random Generation function

In [14]:
np.random.rand(10)

array([5.94750351e-01, 2.53574757e-01, 7.70439087e-01, 4.32976953e-01,
       9.15521878e-02, 5.48424582e-04, 6.40217288e-01, 3.14974401e-01,
       4.31236829e-01, 8.80143498e-01])

In [15]:
np.random.randn(10)

array([-0.8116965 ,  0.3866801 , -0.47908148,  0.44738043,  0.50420915,
        1.30742523,  1.20393341, -1.50761378,  1.53531989,  1.21460774])

In [16]:
np.random.randint(10,20,10)

array([18, 19, 15, 17, 10, 19, 16, 11, 13, 18])

## Array Attributes

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int32')

## Array Methods

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.min()

1

In [25]:
arr.max()

9

In [26]:
arr.sum()

45

In [27]:
np.sum(arr, axis=0) # column sum

array([12, 15, 18])

In [28]:
np.sum(arr, axis=1) # row sum

array([ 6, 15, 24])

In [29]:
arr.mean()

5.0

In [30]:
arr.std()

2.581988897471611

In [31]:
arr.argmax() #it retuens max element index potion

8

In [32]:
arr.argmin() #it return min element index potion

0

## Reshaping and resizing

In [34]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

## Numpy Indexing and Slicing of Vectors

In [38]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
arr[9]

20

In [40]:
arr[1:5]

array([12, 13, 14, 15])

In [41]:
arr[3::2]

array([14, 16, 18, 20])

## Numpy Indexing and Scling of Matrix

In [43]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [44]:
arr[0,0]

1

In [45]:
arr[:2, 1:3]

array([[2, 3],
       [7, 8]])

In [46]:
arr[:,3] # slice 3 column only

array([ 4,  9, 14, 19, 24, 29])

## Boolean Indexing

In [48]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [50]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Array Operation

### Arithmetic operation

In [111]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [113]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [115]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [117]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [119]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [121]:
a1 // a2

array([0, 0, 0, 0, 0])

In [123]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

### Broadcasting

In [127]:
l = [10,20,30,40] # list
arr = np.array(l) # array

In [129]:
l + 10

TypeError: can only concatenate list (not "int") to list

In [131]:
arr + 10

array([20, 30, 40, 50])

### Deep and Shallow copy

In [141]:
# shallow copy
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [145]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [147]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [172]:
s = np.arange(1,11)
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
d = s.copy()
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [176]:
d[0] = 100

In [178]:
d

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [180]:
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
# Deep copy 
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
y = x
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
y[0] = 100

In [168]:
y

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [170]:
x

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

### Matrix operations

In [192]:
# Multiplication in matrix
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [194]:
A

array([[1, 2],
       [3, 4]])

In [196]:
B

array([[5, 6],
       [7, 8]])

In [207]:
A @ B # Multiplication

array([[19, 22],
       [43, 50]])

In [202]:
np.dot(A, B) # Multiplication

array([[19, 22],
       [43, 50]])

In [204]:
# Transpose
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

### Stacking Array

In [213]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [218]:
np.vstack((a,b)) # vertically stack 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [222]:
np.hstack((a,b)) # horizontally stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [224]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting Array

In [228]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [234]:
np.hsplit(c, 2) ## here we can only equal division

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [236]:
np.hsplit(c, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [242]:
np.vsplit(c, 2) ## here we can only equal division

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [244]:
np.vsplit(c, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]